<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="APPY-PC" name="ReporterTest1" tests="4" failures="2" timestamp="25 Oct 2017 19:58:11 GMT" time="64.047" errors="0">
  <testcase name="test1" time="0.811" classname="scripts.Script01"/>
  <testcase name="test2" time="4.725" classname="scripts.Script01"/>
  <testcase name="test3" time="1.182" classname="scripts.Script01">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at scripts.Script01.test3(Script01.java:40)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="3.549" classname="scripts.Script01">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at scripts.Script01.test4(Script01.java:46)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
</testsuite> <!-- ReporterTest1 -->
